# US - Baby Names



### Step 1. Import the necessary libraries

In [2]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset

In [5]:
df=pd.read_csv('6_US_Baby_Names.csv')

### Step 3. Assign it to a variable called baby_names.

In [11]:
baby_names=df
baby_names

         Unnamed: 0       Id     Name  Year Gender State  Count
0             11349    11350     Emma  2004      F    AK     62
1             11350    11351  Madison  2004      F    AK     48
2             11351    11352   Hannah  2004      F    AK     46
3             11352    11353    Grace  2004      F    AK     44
4             11353    11354    Emily  2004      F    AK     41
...             ...      ...      ...   ...    ...   ...    ...
1016390     5647421  5647422     Seth  2014      M    WY      5
1016391     5647422  5647423  Spencer  2014      M    WY      5
1016392     5647423  5647424     Tyce  2014      M    WY      5
1016393     5647424  5647425   Victor  2014      M    WY      5
1016394     5647425  5647426   Waylon  2014      M    WY      5

[1016395 rows x 7 columns]

### Step 4. See the first 10 entries

In [12]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [50]:
baby_names.drop(['Unnamed: 0', 'Id'],axis=1,  inplace=True)
baby_names

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

### Step 6. Is there more male or female names in the dataset?

In [24]:
baby_names['Gender'].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 7. Group the dataset by name and assign to names

In [73]:
names = baby_names.groupby('Name').agg(Counts=('Name','count')).reset_index()
names

          Name  Counts
0        Aaban       2
1        Aadan       4
2      Aadarsh       1
3        Aaden     196
4       Aadhav       1
...        ...     ...
17627     Zyra       7
17628    Zyrah       2
17629    Zyren       1
17630    Zyria      10
17631   Zyriah       9

[17632 rows x 2 columns]

### Step 8. How many different names exist in the dataset?

In [60]:
names.nunique()

         Year  Gender  State  Count
Name
Aaban       2       1      1      1
Aadan       3       1      2      3
Aadarsh     1       1      1      1
Aaden       9       1     45     43
Aadhav      1       1      1      1
...       ...     ...    ...    ...
Zyra        5       1      3      4
Zyrah       2       1      2      2
Zyren       1       1      1      1
Zyria       7       1      3      3
Zyriah      8       1      3      5

[17632 rows x 4 columns]

### Step 9. What is the name with most occurrences?

In [32]:
names.size().sort_values(ascending=False).head(1)

Name
Riley    1112
dtype: int64

### Step 10. How many different names have the least occurrences?

In [74]:
names.sort_values('Counts',inplace=True)
names[names.Counts==1].size

7364

### Step 11. What is the median name occurrence?

In [65]:
names['Name'].count().median()

np.float64(8.0)

### Step 12. What is the standard deviation of names?

In [41]:
name_counts = baby_names.groupby('Name').size()

name_counts.std()

np.float64(122.0299635081389)

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [66]:
name_counts = baby_names.groupby('Name').size()

name_counts.describe()

count    17632.000000
mean        57.644907
std        122.029964
min          1.000000
25%          2.000000
50%          8.000000
75%         39.000000
max       1112.000000
dtype: float64