# US - Baby Names



### Step 1. Import the necessary libraries

In [35]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset

In [36]:
df=pd.read_csv('6_US_Baby_Names.csv')

### Step 3. Assign it to a variable called baby_names.

In [37]:
baby_names=df
baby_names

         Unnamed: 0       Id     Name  Year Gender State  Count
0             11349    11350     Emma  2004      F    AK     62
1             11350    11351  Madison  2004      F    AK     48
2             11351    11352   Hannah  2004      F    AK     46
3             11352    11353    Grace  2004      F    AK     44
4             11353    11354    Emily  2004      F    AK     41
...             ...      ...      ...   ...    ...   ...    ...
1016390     5647421  5647422     Seth  2014      M    WY      5
1016391     5647422  5647423  Spencer  2014      M    WY      5
1016392     5647423  5647424     Tyce  2014      M    WY      5
1016393     5647424  5647425   Victor  2014      M    WY      5
1016394     5647425  5647426   Waylon  2014      M    WY      5

[1016395 rows x 7 columns]

### Step 4. See the first 10 entries

In [38]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [39]:
baby_names.drop(['Unnamed: 0', 'Id'],axis=1,  inplace=True)
baby_names

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

### Step 6. Is there more male or female names in the dataset?

In [40]:
baby_names['Gender'].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 7. Group the dataset by name and assign to names

In [41]:
names = baby_names.groupby('Name').agg(Counts=('Name','count')).reset_index()
names

          Name  Counts
0        Aaban       2
1        Aadan       4
2      Aadarsh       1
3        Aaden     196
4       Aadhav       1
...        ...     ...
17627     Zyra       7
17628    Zyrah       2
17629    Zyren       1
17630    Zyria      10
17631   Zyriah       9

[17632 rows x 2 columns]

### Step 8. How many different names exist in the dataset?

In [42]:
names.nunique()

Name      17632
Counts      651
dtype: int64

### Step 9. What is the name with most occurrences?

In [43]:
names.size().sort_values(ascending=False).head(1)

TypeError: 'int' object is not callable

### Step 10. How many different names have the least occurrences?

In [ ]:
names.sort_values('Counts',inplace=True)
names[names.Counts==1].size

7364

### Step 11. What is the median name occurrence?

In [ ]:
names['Name'].count().median()

np.float64(8.0)

### Step 12. What is the standard deviation of names?

In [ ]:
name_counts = baby_names.groupby('Name').size()

name_counts.std()

np.float64(122.0299635081389)

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [ ]:
# name_counts = baby_names.groupby('Name').size()

name_counts.describe()

NameError: name 'name_counts' is not defined

## exercise 7 start from here

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('7_ecommerce_sales_1000_records.csv')
df

,Order_ID,Product,Category,Quantity,Price,City,Date
0,ORD1001,Backpack,Accessories,1,1629.00,Hyderabad,2026-03-04
1,ORD1002,Keyboard,Electronics,2,1570.94,Surat,2026-01-23
2,ORD1003,Book,Books,4,407.86,Mumbai,2026-02-25
3,ORD1004,Keyboard,Electronics,5,1530.61,Surat,2026-02-20
4,ORD1005,Tablet,Electronics,5,27549.31,Jaipur,2026-05-31
...,...,...,...,...,...,...,...
995,ORD1996,Watch,Accessories,5,4711.82,Ahmedabad,2026-05-22
996,ORD1997,T-Shirt,Fashion,5,861.96,Surat,2026-05-01
997,ORD1998,Backpack,Accessories,2,1751.69,Bangalore,2026-05-31
998,ORD1999,Tablet,Electronics,3,25949.74,Surat,2026-05-11
999,ORD2000,Smartphone,Electronics,4,17509.92,Ahmedabad,2026-06-19

In [ ]:
sales=df
sales

,Order_ID,Product,Category,Quantity,Price,City,Date
0,ORD1001,Backpack,Accessories,1,1629.00,Hyderabad,2026-03-04
1,ORD1002,Keyboard,Electronics,2,1570.94,Surat,2026-01-23
2,ORD1003,Book,Books,4,407.86,Mumbai,2026-02-25
3,ORD1004,Keyboard,Electronics,5,1530.61,Surat,2026-02-20
4,ORD1005,Tablet,Electronics,5,27549.31,Jaipur,2026-05-31
...,...,...,...,...,...,...,...
995,ORD1996,Watch,Accessories,5,4711.82,Ahmedabad,2026-05-22
996,ORD1997,T-Shirt,Fashion,5,861.96,Surat,2026-05-01
997,ORD1998,Backpack,Accessories,2,1751.69,Bangalore,2026-05-31
998,ORD1999,Tablet,Electronics,3,25949.74,Surat,2026-05-11
999,ORD2000,Smartphone,Electronics,4,17509.92,Ahmedabad,2026-06-19

In [ ]:
sales.head(10)

  Order_ID     Product     Category  Quantity     Price       City        Date
0  ORD1001    Backpack  Accessories         1   1629.00  Hyderabad  2026-03-04
1  ORD1002    Keyboard  Electronics         2   1570.94      Surat  2026-01-23
2  ORD1003        Book        Books         4    407.86     Mumbai  2026-02-25
3  ORD1004    Keyboard  Electronics         5   1530.61      Surat  2026-02-20
4  ORD1005      Tablet  Electronics         5  27549.31     Jaipur  2026-05-31
5  ORD1006     T-Shirt      Fashion         1    840.36      Delhi  2026-06-28
6  ORD1007       Watch  Accessories         3   4776.92  Bangalore  2026-03-28
7  ORD1008  Smartphone  Electronics         1  17567.74       Pune  2026-03-30
8  ORD1009        Book        Books         3    477.64     Jaipur  2026-05-18
9  ORD1010  Smartphone  Electronics         4  16483.68  Hyderabad  2026-06-10

In [ ]:
sales.shape()

NameError: name 'sales' is not defined

In [ ]:
sales.count(0)

Order_ID    1000
Product     1000
Category    1000
Quantity    1000
Price       1000
City        1000
Date        1000
dtype: int64

In [ ]:
print(sales.columns)

Index(['Order_ID', 'Product', 'Category', 'Quantity', 'Price', 'City', 'Date'], dtype='str')

In [ ]:
sales.index

RangeIndex(start=0, stop=1000, step=1)

In [ ]:
sales.dtypes

NameError: name 'sales' is not defined

In [ ]:
# 10 number  here

In [ ]:
# 11
sales.nunique()

NameError: name 'sales' is not defined

In [ ]:
# 12
sales
sales['Quantity'].max()

NameError: name 'sales' is not defined

In [ ]:
# 13 
sales.groupby('Product')['Quantity'].sum().max()

NameError: name 'sales' is not defined

In [ ]:
# 14
sales.groupby('Category')['Revenue'].sum().idxmax()

'Electronics'

In [ ]:
# 15
sales['City'].value_counts().idxmax()

'Mumbai'

In [ ]:
# 16
sales.Quantity.sum()

np.int64(1000)

In [ ]:
# 17
sales['Revenue'].sum()

np.float64(27620651.09)

In [ ]:
sales

,Order_ID,Product,Category,Quantity,Price,City,Date
0,ORD1001,Backpack,Accessories,1,1629.00,Hyderabad,2026-03-04
1,ORD1002,Keyboard,Electronics,2,1570.94,Surat,2026-01-23
2,ORD1003,Book,Books,4,407.86,Mumbai,2026-02-25
3,ORD1004,Keyboard,Electronics,5,1530.61,Surat,2026-02-20
4,ORD1005,Tablet,Electronics,5,27549.31,Jaipur,2026-05-31
...,...,...,...,...,...,...,...
995,ORD1996,Watch,Accessories,5,4711.82,Ahmedabad,2026-05-22
996,ORD1997,T-Shirt,Fashion,5,861.96,Surat,2026-05-01
997,ORD1998,Backpack,Accessories,2,1751.69,Bangalore,2026-05-31
998,ORD1999,Tablet,Electronics,3,25949.74,Surat,2026-05-11
999,ORD2000,Smartphone,Electronics,4,17509.92,Ahmedabad,2026-06-19

In [ ]:
# 18
sales.Revenue.mean()

np.float64(8940.486210000001)

In [ ]:
# 19
sales.groupby('Product')['Revenue'].sum().idxmax()

'Laptop'

In [ ]:
# 20
sales.groupby('City')['Revenue'].sum().idxmax()

'Pune'

In [ ]:
# 21 
sales.groupby('Date')['Revenue'].sum().idxmax()

'2026-04-27'

In [45]:
# 22 / 
sales.groupby('Category')['Price'].mean().idxmax()

NameError: name 'sales' is not defined

In [ ]:
# 23 
sales.groupby('Product')['Quantity'].sum().sort_values(ascending=False).head(10)

Product
T-Shirt      259
Backpack     241
Watch        241
Air Fryer    239
Mixer        226
Keyboard     218
Tablet       215
Jeans        214
Laptop       207
Shoes        206
Name: Quantity, dtype: int64

In [ ]:
# 24 
sales.groupby('City')['Revenue'].sum().sort_values(ascending=False).head(5)

City
Pune         3262077.43
Mumbai       3213056.46
Jaipur       3161091.50
Bangalore    3148292.69
Kolkata      2971339.46
Name: Revenue, dtype: float64

In [ ]:
# 25 
sales.groupby('Product')['Price'].mean().idxmax()

'Laptop'

In [ ]:
# 26
sales.Quantity.mean()

np.float64(3.035)

In [ ]:
# 27 
sales['Category'].value_counts()

Category
Electronics        328
Fashion            226
Home Appliances    219
Accessories        161
Books               66
Name: count, dtype: int64

In [ ]:
# 28 
sales.groupby('Revenue')['Category'].value_counts()

Revenue    Category
410.56     Books          1
412.56     Books          1
442.73     Books          1
445.18     Books          1
452.55     Books          1
                         ..
282239.45  Electronics    1
292716.00  Electronics    1
296070.35  Electronics    1
296132.90  Electronics    1
299643.45  Electronics    1
Name: count, Length: 1000, dtype: int64

In [ ]:
# 29
sales.Price.sort_values(ascending=False).head(10)

504    60347.51
108    60323.30
465    60008.45
630    59970.26
685    59935.48
154    59928.69
752    59923.15
428    59899.23
546    59897.07
533    59808.76
Name: Price, dtype: float64

In [ ]:
# 30 
sales['Revenue']=sales['Quantity']*sales['Price']
sales

,Order_ID,Product,Category,Quantity,Price,City,Date,Revenue
0,ORD1001,Backpack,Accessories,1,1629.00,Hyderabad,2026-03-04,1629.00
1,ORD1002,Keyboard,Electronics,2,1570.94,Surat,2026-01-23,3141.88
2,ORD1003,Book,Books,4,407.86,Mumbai,2026-02-25,1631.44
3,ORD1004,Keyboard,Electronics,5,1530.61,Surat,2026-02-20,7653.05
4,ORD1005,Tablet,Electronics,5,27549.31,Jaipur,2026-05-31,137746.55
...,...,...,...,...,...,...,...,...
995,ORD1996,Watch,Accessories,5,4711.82,Ahmedabad,2026-05-22,23559.10
996,ORD1997,T-Shirt,Fashion,5,861.96,Surat,2026-05-01,4309.80
997,ORD1998,Backpack,Accessories,2,1751.69,Bangalore,2026-05-31,3503.38
998,ORD1999,Tablet,Electronics,3,25949.74,Surat,2026-05-11,77849.22
999,ORD2000,Smartphone,Electronics,4,17509.92,Ahmedabad,2026-06-19,70039.68