### Step 1. Import the necessary libraries.

### Step 2. Import the dataset.

### Step 3. Assign it to a variable called music.
### Step 4. Display the first 10 rows of the dataset.
### Step 5. What is the number of observations (rows) in the dataset?
### Step 6. What is the number of columns in the dataset?
### Step 7. Print the names of all the columns.
### Step 8. Display the data types of each column.
### Step 9. How is the dataset indexed?
### Step 10. Display the last 10 rows of the dataset.
### Step 11. Which country has the highest number of listeners?
### Step 12. Which music platform is used by the most listeners?
### Step 13. How many users have Premium and Free subscriptions?
### Step 14. Which is the most popular music genre?
### Step 15. Which artist appears most frequently as the users' top artist?
### Step 16. What is the average daily listening time (in minutes) of all users?
### Step 17. Which listener has the highest daily listening time?
### Step 18. What is the average number of songs listened to per day?
### Step 19. Which country has the highest average daily listening time?
### Step 20. What is the average skip rate percentage across all users?
### Step 21. How many users have enabled offline mode?
### Step 22. How many users listen to podcasts along with music?
### Step 23. What percentage of users use the Discover Weekly feature?
### Step 24. Which mood (top_mood) is the most common among listeners?
### Step 25. What is the average number of playlists created by users?
### Step 26. Which platform has the highest average listening time?
### Step 27. Compare the average listening time of Premium vs Free subscribers.
### Step 28. Which genre has the highest average daily listening time?
### Step 29. Which country has the largest number of Premium subscribers?
### Step 30. Create a summary table showing the average listening minutes, songs per day, and skip rate for each platform.

In [ ]:

# 1
import numpy as np
import pandas as pd

In [ ]:
# 2
df=pd.read_csv('8_music_streaming_habits_2026.csv')
df

,listener_id,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
0,1,24,Australia,Apple Music,Free,R&B,Kendrick Lamar,191,54,9,39.3,False,Sleep,False,True
1,2,21,Germany,Spotify,Free,Classical,Drake,249,68,10,18.3,True,Workout,True,True
2,3,32,Japan,Amazon Music,Free,Hip-Hop,Olivia Rodrigo,49,11,11,22.7,True,Sad,False,True
3,4,39,Japan,Apple Music,Free,Pop,Burna Boy,96,22,8,29.4,True,Sad,True,False
4,5,23,India,Spotify,Family,Country,Olivia Rodrigo,100,24,13,37.7,True,Workout,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,26,France,Spotify,Family,Pop,SZA,197,55,6,15.3,False,Workout,True,False
3996,3997,35,Germany,YouTube Music,Free,Rock,Ariana Grande,320,77,13,9.2,True,Sad,False,True
3997,3998,43,India,Apple Music,Free,Hip-Hop,Dua Lipa,99,38,5,14.0,False,Happy,True,True
3998,3999,26,India,Apple Music,Student,Indie,SZA,76,31,7,36.1,False,Happy,False,False
3999,4000,24,UK,Spotify,Premium,Hip-Hop,Dua Lipa,161,49,9,37.8,True,Workout,False,False

In [ ]:
# 3
music=df
music

,listener_id,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
0,1,24,Australia,Apple Music,Free,R&B,Kendrick Lamar,191,54,9,39.3,False,Sleep,False,True
1,2,21,Germany,Spotify,Free,Classical,Drake,249,68,10,18.3,True,Workout,True,True
2,3,32,Japan,Amazon Music,Free,Hip-Hop,Olivia Rodrigo,49,11,11,22.7,True,Sad,False,True
3,4,39,Japan,Apple Music,Free,Pop,Burna Boy,96,22,8,29.4,True,Sad,True,False
4,5,23,India,Spotify,Family,Country,Olivia Rodrigo,100,24,13,37.7,True,Workout,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,26,France,Spotify,Family,Pop,SZA,197,55,6,15.3,False,Workout,True,False
3996,3997,35,Germany,YouTube Music,Free,Rock,Ariana Grande,320,77,13,9.2,True,Sad,False,True
3997,3998,43,India,Apple Music,Free,Hip-Hop,Dua Lipa,99,38,5,14.0,False,Happy,True,True
3998,3999,26,India,Apple Music,Student,Indie,SZA,76,31,7,36.1,False,Happy,False,False
3999,4000,24,UK,Spotify,Premium,Hip-Hop,Dua Lipa,161,49,9,37.8,True,Workout,False,False

In [ ]:
# 4