### Step 1. Import the necessary libraries.

### Step 2. Import the dataset.

### Step 3. Assign it to a variable called music.
### Step 4. Display the first 10 rows of the dataset.
### Step 5. What is the number of observations (rows) in the dataset?
### Step 6. What is the number of columns in the dataset?
### Step 7. Print the names of all the columns.
### Step 8. Display the data types of each column.
### Step 9. How is the dataset indexed?
### Step 10. Display the last 10 rows of the dataset.
### Step 11. Which country has the highest number of listeners?
### Step 12. Which music platform is used by the most listeners?
### Step 13. How many users have Premium and Free subscriptions?
### Step 14. Which is the most popular music genre?
### Step 15. Which artist appears most frequently as the users' top artist?
### Step 16. What is the average daily listening time (in minutes) of all users?
### Step 17. Which listener has the highest daily listening time?
### Step 18. What is the average number of songs listened to per day?
### Step 19. Which country has the highest average daily listening time?
### Step 20. What is the average skip rate percentage across all users?
### Step 21. How many users have enabled offline mode?
### Step 22. How many users listen to podcasts along with music?
### Step 23. What percentage of users use the Discover Weekly feature?
### Step 24. Which mood (top_mood) is the most common among listeners?
### Step 25. What is the average number of playlists created by users?
### Step 26. Which platform has the highest average listening time?
### Step 27. Compare the average listening time of Premium vs Free subscribers.
### Step 28. Which genre has the highest average daily listening time?
### Step 29. Which country has the largest number of Premium subscribers?
### Step 30. Create a summary table showing the average listening minutes, songs per day, and skip rate for each platform.

In [2]:

# 1
import numpy as np
import pandas as pd

In [3]:
# 2
df=pd.read_csv('8_music_streaming_habits_2026.csv')
df

,listener_id,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
0,1,24,Australia,Apple Music,Free,R&B,Kendrick Lamar,191,54,9,39.3,False,Sleep,False,True
1,2,21,Germany,Spotify,Free,Classical,Drake,249,68,10,18.3,True,Workout,True,True
2,3,32,Japan,Amazon Music,Free,Hip-Hop,Olivia Rodrigo,49,11,11,22.7,True,Sad,False,True
3,4,39,Japan,Apple Music,Free,Pop,Burna Boy,96,22,8,29.4,True,Sad,True,False
4,5,23,India,Spotify,Family,Country,Olivia Rodrigo,100,24,13,37.7,True,Workout,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,26,France,Spotify,Family,Pop,SZA,197,55,6,15.3,False,Workout,True,False
3996,3997,35,Germany,YouTube Music,Free,Rock,Ariana Grande,320,77,13,9.2,True,Sad,False,True
3997,3998,43,India,Apple Music,Free,Hip-Hop,Dua Lipa,99,38,5,14.0,False,Happy,True,True
3998,3999,26,India,Apple Music,Student,Indie,SZA,76,31,7,36.1,False,Happy,False,False
3999,4000,24,UK,Spotify,Premium,Hip-Hop,Dua Lipa,161,49,9,37.8,True,Workout,False,False

In [4]:
# 3
music=df
music

,listener_id,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
0,1,24,Australia,Apple Music,Free,R&B,Kendrick Lamar,191,54,9,39.3,False,Sleep,False,True
1,2,21,Germany,Spotify,Free,Classical,Drake,249,68,10,18.3,True,Workout,True,True
2,3,32,Japan,Amazon Music,Free,Hip-Hop,Olivia Rodrigo,49,11,11,22.7,True,Sad,False,True
3,4,39,Japan,Apple Music,Free,Pop,Burna Boy,96,22,8,29.4,True,Sad,True,False
4,5,23,India,Spotify,Family,Country,Olivia Rodrigo,100,24,13,37.7,True,Workout,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,26,France,Spotify,Family,Pop,SZA,197,55,6,15.3,False,Workout,True,False
3996,3997,35,Germany,YouTube Music,Free,Rock,Ariana Grande,320,77,13,9.2,True,Sad,False,True
3997,3998,43,India,Apple Music,Free,Hip-Hop,Dua Lipa,99,38,5,14.0,False,Happy,True,True
3998,3999,26,India,Apple Music,Student,Indie,SZA,76,31,7,36.1,False,Happy,False,False
3999,4000,24,UK,Spotify,Premium,Hip-Hop,Dua Lipa,161,49,9,37.8,True,Workout,False,False

In [5]:
# 4
music.head(10)

,listener_id,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
0,1,24,Australia,Apple Music,Free,R&B,Kendrick Lamar,191,54,9,39.3,False,Sleep,False,True
1,2,21,Germany,Spotify,Free,Classical,Drake,249,68,10,18.3,True,Workout,True,True
2,3,32,Japan,Amazon Music,Free,Hip-Hop,Olivia Rodrigo,49,11,11,22.7,True,Sad,False,True
3,4,39,Japan,Apple Music,Free,Pop,Burna Boy,96,22,8,29.4,True,Sad,True,False
4,5,23,India,Spotify,Family,Country,Olivia Rodrigo,100,24,13,37.7,True,Workout,True,True
5,6,41,Australia,Tidal,Free,Rock,Olivia Rodrigo,64,19,10,12.0,True,Energetic,False,True
6,7,13,Australia,Spotify,Free,EDM,Burna Boy,193,53,7,20.3,True,Sleep,False,False
7,8,22,India,SoundCloud,Premium,Hip-Hop,Bad Bunny,142,44,7,33.3,False,Workout,False,False
8,9,40,Australia,Spotify,Free,Hip-Hop,Bad Bunny,120,38,7,15.4,True,Happy,False,True
9,10,27,Nigeria,Spotify,Student,Hip-Hop,Burna Boy,127,33,8,48.7,True,Happy,False,True

In [6]:
# 5
music.shape[0]

4000

In [7]:
# 6
music.shape[1]

15

In [11]:
# 7
music.columns

Index(['listener_id', 'age', 'country', 'platform', 'subscription',
       'top_genre', 'top_artist', 'daily_listening_minutes', 'songs_per_day',
       'playlists_count', 'skip_rate_pct', 'discover_weekly_user', 'top_mood',
       'uses_offline_mode', 'podcasts_too'],
      dtype='str')

In [12]:
# 8
music.dtypes

listener_id                  int64
age                          int64
country                        str
platform                       str
subscription                   str
top_genre                      str
top_artist                     str
daily_listening_minutes      int64
songs_per_day                int64
playlists_count              int64
skip_rate_pct              float64
discover_weekly_user          bool
top_mood                       str
uses_offline_mode             bool
podcasts_too                  bool
dtype: object

In [13]:
# 9
music.index

RangeIndex(start=0, stop=4000, step=1)

In [14]:
# 10
music.tail(10)

,listener_id,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
3990,3991,27,Canada,Spotify,Free,R&B,Travis Scott,165,53,9,24.7,True,Happy,False,False
3991,3992,40,Canada,Apple Music,Family,Pop,Olivia Rodrigo,76,18,7,41.6,False,Focus,False,False
3992,3993,35,USA,Spotify,Free,Hip-Hop,The Weeknd,55,19,13,57.3,False,Chill,True,True
3993,3994,37,USA,Spotify,Free,Hip-Hop,Travis Scott,57,20,3,31.9,True,Energetic,True,False
3994,3995,30,Nigeria,Apple Music,Family,Rock,Travis Scott,303,90,10,13.5,True,Sad,True,True
3995,3996,26,France,Spotify,Family,Pop,SZA,197,55,6,15.3,False,Workout,True,False
3996,3997,35,Germany,YouTube Music,Free,Rock,Ariana Grande,320,77,13,9.2,True,Sad,False,True
3997,3998,43,India,Apple Music,Free,Hip-Hop,Dua Lipa,99,38,5,14.0,False,Happy,True,True
3998,3999,26,India,Apple Music,Student,Indie,SZA,76,31,7,36.1,False,Happy,False,False
3999,4000,24,UK,Spotify,Premium,Hip-Hop,Dua Lipa,161,49,9,37.8,True,Workout,False,False

In [23]:
# 11
music.groupby('country').agg({'listener_id':'count'})

           listener_id
country
Australia          397
Brazil             409
Canada             429
France             377
Germany            371
India              390
Japan              439
Nigeria            401
UK                 369
USA                418

In [24]:
# 12 
music.groupby('platform').agg({'listener_id':'count'})

               listener_id
platform
Amazon Music           315
Apple Music            906
SoundCloud             278
Spotify               1591
Tidal                  221
YouTube Music          689

In [73]:
# 13
a=music.groupby('subscription').agg({'listener_id':'count'})
a
b=a.sort_values('listener_id')[0:3].sum()
c=a.sort_values('listener_id')[3:].sum()
print(f'total free sub:{c.values}and total pre listner vlaues: {b.values}')

total free sub:[1820]and total pre listner vlaues: [2180]

In [35]:
# 14
a=music.groupby('top_genre').agg({'listener_id':'count'})
a.sort_values('listener_id').tail(1)

           listener_id
top_genre
Pop                721

In [36]:
# 15
music.top_artist.max()

'Tyler the Creator'

In [37]:
# 16
music.daily_listening_minutes.mean()

np.float64(138.70275)

In [42]:
# 17 
music.sort_values('daily_listening_minutes').tail(1)

,listener_id,age,country,platform,subscription,top_genre,top_artist,daily_listening_minutes,songs_per_day,playlists_count,skip_rate_pct,discover_weekly_user,top_mood,uses_offline_mode,podcasts_too
1522,1523,20,Japan,Amazon Music,Family,Hip-Hop,Drake,697,198,10,23.9,False,Sleep,True,False

In [43]:
# 18 
music.songs_per_day.mean()

np.float64(39.1375)

In [55]:
# 19 

a=music.groupby('country').agg({'daily_listening_minutes':'mean'})
a.sort_values('daily_listening_minutes').tail(1)

         daily_listening_minutes
country
Canada                143.097902

In [57]:
# 20 
a=music.groupby('skip_rate_pct').agg({'listener_id':'mean'})
a.sort_values('skip_rate_pct').tail(1)

               listener_id
skip_rate_pct
70.9                 611.0

In [ ]:
# 21 
a=music.groupby('uses_offline_mode').agg({'listener_id':'count'})
a.tail(1)

music[music.uses_offline_mode==True].shape[0]

1710

In [66]:
# 22 
music[music.podcasts_too==True].shape[0]

1872

In [67]:
# 23 
music[music.discover_weekly_user==True].shape[0]

2280

In [89]:
# 24 
a=music.groupby('top_mood').agg({'listener_id':'count'})
a.sort_values('listener_id',ascending=False,inplace=True)
a.head(1)

          listener_id
top_mood
Sad               538

In [95]:
# 25 
music.playlists_count.mean()

np.float64(8.9945)

In [ ]:
# 26
a=music.groupby('platform').agg({'platform':'count'})
a.mean()

platform    666.666667
dtype: float64

In [ ]:
# 28
a=music.groupby('top_genre').agg({'daily_listening_minutes':'mean'})
a.sort_values('daily_listening_minutes',ascending=False,inplace=True)
a.head(1)

           daily_listening_minutes
top_genre
Country                 154.660606

In [110]:
# 29
a=music.groupby('country').agg({'subscription':'count'})
a
# b=a.sort_values('listener_id')[0:3].sum()
# c=a.sort_values('listener_id')[3:].sum()
c

listener_id    1820
dtype: int64