In [48]:
import pandas as pd
import numpy as np
arr=np.arange(1,21)
b=pd.Series(arr)
# print(arr)
# print(b)
# print(type(b))
a=[arr,arr,arr,arr]
print(pd.DataFrame(a))
c=pd.DataFrame({'x':arr,'y':arr,"z":arr})
print(c)
# print(pd.DataFrame({'x':arr,'y':arr,"z":arr}))

   0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  \
0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
1   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
2   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
3   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19

   19
0  20
1  20
2  20
3  20
     x   y   z
0    1   1   1
1    2   2   2
2    3   3   3
3    4   4   4
4    5   5   5
5    6   6   6
6    7   7   7
7    8   8   8
8    9   9   9
9   10  10  10
10  11  11  11
11  12  12  12
12  13  13  13
13  14  14  14
14  15  15  15
15  16  16  16
16  17  17  17
17  18  18  18
18  19  19  19
19  20  20  20

In [49]:
import pandas as pd
df=pd.read_csv("data-.csv")
print(df)
print("---------------")

df.head(2)
print("---------------")

df.tail(2)
print("---------------")
df.info()
print("---------------")
df.describe()

    name  age     city category  sales  a   b
0   John   25    Delhi        A    200  5  10
1   Riya   22   Mumbai        B    120  2   3
2   Aman   30     Pune        A    250  7   8
3   Neha   27  Kolkata        C    300  4   6
4  Arjun   35   Jaipur        B    200  1   9
---------------
---------------
---------------
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      5 non-null      str
 1   age       5 non-null      int64
 2   city      5 non-null      str
 3   category  5 non-null      str
 4   sales     5 non-null      int64
 5   a         5 non-null      int64
 6   b         5 non-null      int64
dtypes: int64(4), str(3)
memory usage: 412.0 bytes
---------------

             age       sales         a          b
count   5.000000    5.000000  5.000000   5.000000
mean   27.800000  214.000000  3.800000   7.200000
std     4.969909   66.932802  2.387467   2.774887
min    22.000000  120.000000  1.000000   3.000000
25%    25.000000  200.000000  2.000000   6.000000
50%    27.000000  200.000000  4.000000   8.000000
75%    30.000000  250.000000  5.000000   9.000000
max    35.000000  300.000000  7.000000  10.000000

In [50]:
import numpy as np
arr=np.array([[
    
]])

In [51]:
# sort an row wise
# sort every row of [[9,4,7],[2,8,1],[6,3,5]]
import numpy as np
arr=np.array([
    [9,4,7],
    [2,8,1],
    [6,3,5]])
# print(np.sort(arr))
print(arr.T)

[[9 2 6]
 [4 8 3]
 [7 1 5]]

In [52]:
import numpy as np
import pandas as pd
l=[10,20,30,40,50]
a={"a":10,"b":20,"c":30,"d":40}
s=pd.Series(a)
print(pd.Series(a))
print(pd.Series(l))

a    10
b    20
c    30
d    40
dtype: int64
0    10
1    20
2    30
3    40
4    50
dtype: int64


## Series attribute

**Series attributes**

In [53]:
import numpy as np
import pandas as pd
l=[10,20,30,40,50]
a={"a":10,"b":20,"c":30,"d":40}
s=pd.Series(a)
print(s.size)
print(s.shape)
print(s.dtype)
print(s.is_unique)
print(s.index)
print(s.values)

4
(4,)
int64
True
Index(['a', 'b', 'c', 'd'], dtype='str')
[10 20 30 40]

## series method and methodchaining

In [54]:
import numpy as np
import pandas as pd
l=[10,20,30,40,50]
a={"a":10,"b":20,"c":30,"d":40}
s=pd.Series(a)
print(s.head(2))
print(s.tail(2))

a    10
b    20
dtype: int64
c    30
d    40
dtype: int64

In [55]:
import numpy as np
import pandas as pd
arr=np.arange(100,1000)
s=pd.Series(arr)
# print(s)
s.head(10)
s.tail(10)
s.sample(10)
s.value_counts()
s.sort_values(ascending=False)
s.sort_index()
s.head(100).sample(10).tail(5).sort_values().sort_index()

3     103
31    131
35    135
48    148
55    155
dtype: int64

#mathatical functions

## mathatical function

In [56]:
arr=np.array([1,7,3,np.nan,np.nan,np.nan,8,6,3,2,3,6,7,7,8,8])
# print(arr)
s=pd.Series(arr)
print(s)

0     1.0
1     7.0
2     3.0
3     NaN
4     NaN
5     NaN
6     8.0
7     6.0
8     3.0
9     2.0
10    3.0
11    6.0
12    7.0
13    7.0
14    8.0
15    8.0
dtype: float64

In [57]:
a=s.size
b=s.count()
c=a-b
# print(c)
s.sum()
s.product()
s.mean()
s.mode()
s.std()
s.var()
s.max()
s.min()
s.describe()

count    13.000000
mean      5.307692
std       2.529315
min       1.000000
25%       3.000000
50%       6.000000
75%       7.000000
max       8.000000
dtype: float64

## indexing and slicing

In [58]:
s.iloc[1]

np.float64(7.0)

In [59]:

# s=pd.Series([10,20,30,40,50],index=[])
# s.loc["a"]
# s.loc["c"]
# s.loc["b"]
# s.loc["e"]
# s.loc[['a','c']]
# s.iloc[2:5]
# s.loc[2:5]

## editing a series

In [60]:
import pandas as pd
s=pd.Series([10,20,30,40,50],index=['a','b','c','d','e'])
s[0]=100

s[0]
s[7]=19
s[7]
s['a':'c']=[200,300,400]
s['a':'c']=25
print(s)

a     25
b     25
c     25
d     40
e     50
0    100
7     19
dtype: int64

Null value handling

## Null value handling

In [61]:
import numpy as np
arr=np.array([1,7,3,np.nan,np.nan,np.nan,8,6,3,2,3,6,7,7,8,8])
# print(arr)
s=pd.Series(arr)

print(s.isnull().sum())
print(s.notnull().sum())
print(s.hasnans)

3
13
True

## unique values

In [62]:
import numpy as np
arr=np.array([1,7,3,np.nan,np.nan,np.nan,8,6,3,2,3,6,7,7,8,8])
# print(arr)
s=pd.Series(arr)
s.unique()
s.nunique()
s.is_unique

False

In [63]:
import pandas as pd
df=pd.read_csv("1_data.csv")
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [64]:
df[['order_id','quantity']]

      order_id  quantity
0            1         1
1            1         1
2            1         1
3            1         1
4            2         2
...        ...       ...
4617      1833         1
4618      1833         1
4619      1834         1
4620      1834         1
4621      1834         1

[4622 rows x 2 columns]

In [65]:
# acess rows
df[0:4]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39

In [66]:
df[0:10]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [67]:
df.iloc[0:4]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39

In [68]:
df.loc["harse":"sam"]

Empty DataFrame
Columns: [order_id, quantity, item_name, choice_description, item_price]
Index: []

In [69]:
df[['item_price']]
type("item_price")

str

In [70]:
# type cast 
df["item_price"]=df['item_price'].str.replace('$','', regex=False)
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [71]:
df["item_price"]=df['item_price'].str.replace('','', regex=False)
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [72]:
df['item_price'].astype('float')
print(df)
type(df)

      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description item_price
0                                                   NaN      2.39
1                                          [Clementine]      3.39
2                                               [Apple]      3.39
3                                                   NaN      2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     16.98
...                                                 ...        ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...     11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...     11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...      8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...      8.75

[4622 rows x 5 columns]

pandas.DataFrame

In [73]:
df['item_price']

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
         ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: str

In [74]:
# df['item_price'].between(11,16)
df.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [75]:
import pandas as pd
# df.drop(columns=['item_price'],inplace=True),

In [76]:
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [77]:
# df=df.drop(columns=['item_price'])

In [78]:
df['item_price'].unique()

<StringArray>
[ '2.39 ',  '3.39 ', '16.98 ', '10.98 ',  '1.69 ', '11.75 ',  '9.25 ',
  '4.45 ',  '8.75 ', '11.25 ',  '8.49 ',  '2.18 ',  '8.99 ',  '1.09 ',
  '2.95 ',  '2.15 ',  '3.99 ', '22.50 ', '11.48 ', '17.98 ', '17.50 ',
  '4.30 ',  '5.90 ',  '1.25 ', '23.78 ',  '6.49 ', '11.08 ',  '1.50 ',
 '22.16 ', '32.94 ', '22.20 ', '10.58 ',  '2.50 ', '23.50 ',  '7.40 ',
 '18.50 ',  '3.00 ',  '6.78 ', '11.89 ',  '9.39 ',  '4.00 ',  '3.75 ',
  '8.69 ',  '2.29 ',  '8.90 ',  '3.27 ',  '3.89 ',  '8.19 ', '35.00 ',
 '27.75 ', '11.80 ',  '6.00 ', '26.25 ', '21.96 ',  '4.36 ',  '7.50 ',
  '4.78 ', '13.35 ',  '6.45 ',  '5.07 ', '22.96 ',  '7.17 ',  '7.98 ',
  '4.50 ', '26.07 ', '12.98 ', '35.25 ', '44.25 ', '10.50 ', '33.75 ',
 '16.38 ', '13.52 ',  '5.00 ', '15.00 ',  '8.50 ', '17.80 ',  '1.99 ',
 '11.49 ']
Length: 78, dtype: str

In [79]:
df['item_price'].astype('float')
print(df)
type(df)

      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description item_price
0                                                   NaN      2.39
1                                          [Clementine]      3.39
2                                               [Apple]      3.39
3                                                   NaN      2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     16.98
...                                                 ...        ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...     11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...     11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...      8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...      8.75

[4622 rows x 5 columns]

pandas.DataFrame

In [80]:
df['item_price']=pd.to_numeric(df['item_price'])
df['item_price'].between(11,26)
df[df['item_price'].between(11,26)]

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
42,20,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
...,...,...,...,...,...
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25

In [81]:
m=df['item_price'].between(11,26)
df[m]

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
42,20,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25
...,...,...,...,...,...
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25

In [82]:
df.duplicated().sum()

np.int64(59)

In [83]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [84]:
df.isnull().sum().sum()
# df.dropna(inplace=True)
# df.isnull().sum().sum()
# df.fillna(12,inplace=True)
m=df['choice_description'].mode()
df
df.fillna(m,inplace=True)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [85]:
def incr(x):
    if x>10:
        x=x+1
    else:
        x=x+3 
    return x           

df['new_price']=df['item_price'].apply(incr)
df

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,5.39
1,1,1,Izze,[Clementine],3.39,6.39
2,1,1,Nantucket Nectar,[Apple],3.39,6.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,5.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,17.98
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,12.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,12.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,12.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,11.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,11.75

In [86]:
df.set_index('order_id')

,quantity,item_name,choice_description,item_price,new_price
order_id,,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,2.39,5.39
1,1,Izze,[Clementine],3.39,6.39
1,1,Nantucket Nectar,[Apple],3.39,6.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,5.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,17.98
...,...,...,...,...,...
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,12.75
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,12.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,12.25
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,11.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,11.75

In [98]:

df['item_name'].nunique()
z=df.groupby('item_name')
y=z.get_group('Canned Soda')
y

,order_id,quantity,item_name,choice_description,item_price,new_price
18,9,2,Canned Soda,[Sprite],2.18,5.18
28,14,1,Canned Soda,[Dr. Pepper],1.09,4.09
51,23,2,Canned Soda,[Mountain Dew],2.18,5.18
53,24,1,Canned Soda,[Sprite],1.09,4.09
107,47,1,Canned Soda,[Dr. Pepper],1.09,4.09
...,...,...,...,...,...,...
3897,1562,1,Canned Soda,[Mountain Dew],1.09,4.09
3926,1575,1,Canned Soda,[Dr. Pepper],1.09,4.09
3936,1578,1,Canned Soda,[Diet Dr. Pepper],1.09,4.09
4008,1604,1,Canned Soda,[Diet Coke],1.09,4.09
4051,1621,1,Canned Soda,[Sprite],1.09,4.09

In [ ]:
# .concat()
#  .merge() parameter='inner' 'outer','left', 'right'
#  .join()